# This is my alacritty config
# author: Bruno de Lima <github.com/brunodles>


[window]
padding = { x = 8, y = 8 }
dynamic_padding = true
opacity = 0.99
blur = true
startup_mode = "Windowed"
decorations = "Full"
class = { instance = "Alacritty", general = "Alacritty" }
decorations_theme_variant = "Dark"
option_as_alt = "OnlyLeft"

[cursor]
style = { shape = "Block", blinking = "On" }

[font]
#normal = { family = "monospace", style = "Regular" }
#normal = { family = "RobotoMono Nerd Font", style = "Regular" }
#normal = { family = "Terminess Nerd Font Mono", style = "Regular" }
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
#normal = { family = "Ubuntu Mono derivative Powerline", style = "Regular" }
size = 10

